services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker-java/Dockerfile
    ports:
      - '3000:3000'
    networks:
      - myapp

  postgres:
    container_name: postgres
    image: postgres:18-alpine3.24
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/18/docker'
    networks:
      - myapp

volumes:
  db:

networks:
  myapp:
    driver: bridge