services:
  app:
    container_name: app
    image: maven:3.9-eclipse-temurin-21
    working_dir: /back
    tty: true
    command: bash
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres_db
      - SPRING_DATASOURCE_USERNAME=postgres_username
      - SPRING_DATASOURCE_PASSWORD=postgres_password
    volumes:
      - ./:/back
    networks:
      - myapp

  postgres:
    container_name: postgres
    image: postgres:18-alpine3.24
    environment:
      - POSTGRES_DB=postgres_db
      - POSTGRES_USER=postgres_username
      - POSTGRES_PASSWORD=postgres_password
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/18/docker'
    networks:
      - myapp

volumes:
  db:

networks:
  myapp:
    driver: bridge