name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: docker up
        run: docker compose up -d

#      - name: install dependencies
#        run: docker compose exec -T -w /back app mvn package

      - name: build app
        run: docker compose exec -T -w /back app mvn package

      - name: stop docker
        if: always()
        run: docker compose down